name: Test SSH VPS

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: SSH test
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script_stop: true
          script: |
            set -ex
            whoami
            hostname
            pwd
            ls -la /www/wwwroot/dash.oohx.net